version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k7x153ugfhe2"
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "sam-gitlab-webhook"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k7x153ugfhe2"
s3_prefix = "sam-gitlab-webhook"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
